image: spacecowboy/android-docker-builder:25

stages:
  - Build
  - "Compatibility Tests"

before_script:
  - chmod +x ./gradlew

mytest:
  stage: Build
  tags:
    - private
  script:
    - echo "Working dir: $(pwd)"
    - ls -lha
    - touch afile.txt
    - ls -lha /
