image: spacecowboy/android-docker-builder:25

stages:
  - Build
  - "Compatibility Tests"

before_script:
  - chmod +x ./gradlew


#"Compatibility Tests"
android-25:
  stage: Build
  script:
    - chmod +x scripts/android-wait-for-emulator
    - echo y | sdkmanager --update
    - echo y | sdkmanager "emulator" "system-images;android-25;google_apis;armeabi-v7a"
    - echo n | avdmanager create avd --name test --abi google_apis/armeabi-v7a --package "system-images;android-25;google_apis;armeabi-v7a"
    - ${ANDROID_HOME}/emulator/emulator -avd test -no-window -no-audio &
    - scripts/android-wait-for-emulator
    - adb shell input keyevent 82
    - ./gradlew connectedAndroidTest

android-25x86:
  stage: Build
  script:
    - chmod +x scripts/android-wait-for-emulator
    - echo y | sdkmanager --update
    - echo y | sdkmanager "emulator" "system-images;android-25;google_apis;x86"
    - echo n | avdmanager create avd --name test --abi google_apis/x86 --package "system-images;android-25;google_apis;x86"
    - ${ANDROID_HOME}/emulator/emulator64-x86 -avd test -no-window -no-audio &
    - scripts/android-wait-for-emulator
    - adb shell input keyevent 82
    - ./gradlew connectedAndroidTest
