stages:
  - build
  - test
  - test2

image: openjdk:8-jdk

variables:
  ANDROID_HOME: /var/lib/gitlab-runner/android
  ANDROID_COMPILE_SDK: "25"
  ANDROID_BUILD_TOOLS: "25.0.2"
  ADB_INSTALL_TIMEOUT: "8"

.sdk_apt: &before_docker
  before_script:
    - set -euo pipefail
    - apt-get --quiet update --yes
      && apt-get --quiet install --yes --no-install-recommends wget
                                                               tar
                                                               unzip
                                                               lib32stdc++6
                                                               lib32z1
                                                               file
                                                               mesa-utils
                                                               pciutils
      && rm -rf /var/lib/apt/lists/*
    - export PATH="${ANDROID_HOME}/emulator/:${ANDROID_HOME}/tools/bin/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}"
    - ci/before
    - chmod +x ./gradlew

.sdk: &before_metal
  before_script:
    - set -euo pipefail
    - export PATH="${ANDROID_HOME}/emulator/:${ANDROID_HOME}/tools/bin/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}"
    - ci/before
    - chmod +x ./gradlew

.build: &build_def
  <<: *before_docker
  stage: build
  script:
    - ./gradlew assemble assembleAndroidTest
  artifacts:
    expire_in: 1 week
    untracked: true

.test: &test_def
  <<: *before_docker
  stage: test
  script:
    - ./gradlew check
  dependencies:
    - build:jdk-1.8
  artifacts:
    paths:
      - app/build/reports

.arm_test: &arm_def
  <<: *before_docker
  stage: test
  script:
    - ci/emulator-tests ${ANDROID_EMULATOR_SDK} armeabi-v7a
  dependencies:
    - build:jdk-1.8
  artifacts:
    paths:
      - app/build/reports

.emulator_test: &emulator_def
  <<: *before_metal
  tags:
    - metal
    - android
  stage: test2
  script:
    - ci/emulator-tests ${ANDROID_EMULATOR_SDK}
  dependencies:
    - build:jdk-1.8
  artifacts:
    paths:
      - app/build/reports


build:jdk-1.8:
  <<: *build_def

unit-tests:jdk-1.8:
  <<: *test_def

test:x86-18:
  <<: *emulator_def
  variables:
    ANDROID_EMULATOR_SDK: "18"

test:x86-25:
  <<: *emulator_def
  variables:
    ANDROID_EMULATOR_SDK: "25"

test:x86-26:
  <<: *emulator_def
  variables:
    ANDROID_EMULATOR_SDK: "26"

test:arm-18:
  <<: *arm_def
  variables:
    ANDROID_EMULATOR_SDK: "18"

test:arm-19:
  <<: *arm_def
  variables:
    ANDROID_EMULATOR_SDK: "19"

test:arm-20:
  <<: *arm_def
  variables:
    ANDROID_EMULATOR_SDK: "20"

test:arm-21:
  <<: *arm_def
  variables:
    ANDROID_EMULATOR_SDK: "21"

test:arm-22:
  <<: *arm_def
  variables:
    ANDROID_EMULATOR_SDK: "22"

test:arm-23:
  <<: *arm_def
  variables:
    ANDROID_EMULATOR_SDK: "23"

test:arm-24:
  <<: *arm_def
  variables:
    ANDROID_EMULATOR_SDK: "24"

test:arm-25:
  <<: *arm_def
  variables:
    ANDROID_EMULATOR_SDK: "25"
