stages:
  - build
  - test

image: openjdk:8-jdk

variables:
  ANDROID_HOME: /var/lib/gitlab-runner/android
  ANDROID_COMPILE_SDK: "25"
  ANDROID_BUILD_TOOLS: "25.0.2"

.sdk_apt: &before_docker
  before_script:
    - set -euo pipefail
    - apt-get --quiet update --yes
      && apt-get --quiet install --yes --no-install-recommends wget
                                                               tar
                                                               unzip
                                                               lib32stdc++6
                                                               lib32z1
                                                               file
                                                               mesa-utils
                                                               pciutils
      && rm -rf /var/lib/apt/lists/*
    - export PATH="${ANDROID_HOME}/emulator/:${ANDROID_HOME}/tools/bin/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}"
    - ci/before
    - chmod +x ./gradlew

.sdk: &before_metal
  before_script:
    - set -euo pipefail
    - export PATH="${ANDROID_HOME}/emulator/:${ANDROID_HOME}/tools/bin/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}"
    - ci/before
    - chmod +x ./gradlew

.build: &build_def
  <<: *before_docker
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
    - app/build/outputs/

.test: &test_def
  <<: *before_docker
  stage: build
  script:
    - ./gradlew check
  artifacts:

.emulator_test: &emulator_def
  <<: *before_metal
  tags:
    - metal
    - android
  stage: build
  script:
    - ci/emulator-tests ${ANDROID_EMULATOR_SDK}
  artifacts:
    paths:
      - app/build/reports/androidTests/

build:jdk-1.8:
  <<: *build_def

unit-tests:jdk-1.8:
  <<: *test_def

test:emulator-18:
  <<: *emulator_def
  variables:
    ANDROID_EMULATOR_SDK: "18"

test:emulator-25:
  <<: *emulator_def
  variables:
    ANDROID_EMULATOR_SDK: "25"

test:emulator-26:
  <<: *emulator_def
  variables:
    ANDROID_EMULATOR_SDK: "26"
