image: spacecowboy/android-docker-builder:25

stages:
  - Build
  - "Compatibility Tests"

before_script:
  - chmod +x ./gradlew


#     - echo no | ${ANDROID_HOME}/tools/bin/avdmanager create avd -n test -t android-18 --abi google_apis/x86

#"Compatibility Tests"
android-25:
  stage: Build
  script:
    - chmod +x scripts/android-wait-for-emulator
    - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "system-images;android-25;google_apis;x86"
    - echo n | ${ANDROID_HOME}/tools/android create avd -n test -t android-25
    - ${ANDROID_HOME}/tools/emulator64-x86 -avd test -no-window -no-audio &
    - scripts/android-wait-for-emulator
    - ${ANDROID_HOME}/platform-tools/adb shell input keyevent 82
    - ./gradlew connectedAndroidTest
