stages:
  - build
  - test

image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "27"
  ANDROID_BUILD_TOOLS: "27.0.1"

cache:
  paths:
     - .gradle/

.sdk_apt: &before_docker
  before_script:
    - set -euo pipefail
    - apt-get --quiet update --yes
      && apt-get --quiet install --yes --no-install-recommends wget
                                                               tar
                                                               unzip
                                                               lib32stdc++6
                                                               lib32z1
                                                               file
                                                               mesa-utils
                                                               pciutils
      && rm -rf /var/lib/apt/lists/*
    - export GRADLE_USER_HOME="$(pwd)/.gradle"
    - export ANDROID_HOME="$(pwd)/.androidhome"
    - export PATH="${ANDROID_HOME}/emulator/:${ANDROID_HOME}/tools/bin/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}"
    - ci/before
    - chmod +x ./gradlew

.sdk: &before_metal
  before_script:
    - set -euo pipefail
    - export GRADLE_USER_HOME="$(pwd)/.gradle"
    - export ANDROID_HOME="$(pwd)/.androidhome"
    - export PATH="${ANDROID_HOME}/emulator/:${ANDROID_HOME}/tools/bin/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}"
    - ci/before
    - chmod +x ./gradlew

.build: &build_def
  <<: *before_docker
  stage: build
  script:
    - ./gradlew assemble -PdisablePreDex
  artifacts:
    paths:
    - app/build/outputs/
    - build/logs/

.test: &test_def
  <<: *before_docker
  stage: build
  script:
    - ./gradlew check -PdisablePreDex
  artifacts:

.emulator_test: &emulator_def
  <<: *before_metal
  tags:
    - metal
    - android
  stage: test
  script:
    - ci/emulator-tests ${ANDROID_EMULATOR_SDK}
  artifacts:
    paths:
      - app/build/reports/androidTests/
      - build/logs/

build:jdk-1.8:
  <<: *build_def

unit-tests:jdk-1.8:
  <<: *test_def

#test:emulator-18:
#  <<: *emulator_def
#  variables:
#    ANDROID_EMULATOR_SDK: "18"

#test:emulator-25:
#  <<: *emulator_def
#  variables:
#    ANDROID_EMULATOR_SDK: "25"

#test:emulator-26:
#  <<: *emulator_def
#  variables:
#    ANDROID_EMULATOR_SDK: "26"
