image: spacecowboy/android-docker-builder:25

before_script:
  - chmod +x ./gradlew

build:
  tags:
    - android
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

test:
  tags:
    - android
  script:
    - ./gradlew check
  artifacts:
